//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GieAndVince.Models.Db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MenuRecipe
    {

        public int MIRID { get; set; }
        public string MIRName { get; set; }
        public int MIRPrice { get; set; }
        public string MIRRecipe { get; set; }
    }
}
