//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GieAndVince.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesperYear
    {
        public int SPYearId { get; set; }
        public int SPYearDate { get; set; }
        public decimal SPYearSales { get; set; }
    }
}
