//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GieAndVince.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesperDay
    {
        public int SPDayId { get; set; }
        public System.DateTime SPDayDate { get; set; }
        public decimal SPDaySales { get; set; }
    }
}
