//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GieAndVince.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesManagement
    {
        public int SalesManagementId { get; set; }
        public int SPDayId { get; set; }
        public int SPWeekId { get; set; }
        public int SPMonthId { get; set; }
        public int SPYearId { get; set; }
        public string CalendarDateType { get; set; }
        public decimal TotalSales { get; set; }
    }
}
